[package]
name = "wasmtime-tools"
authors = ["The Wasmtime Project Developers"]
version = "0.1.0"
description = "Command-line interface for the wasmtime crate"
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://cranelift.readthedocs.io/"
categories = ["wasm"]
repository = "https://github.com/CraneStation/wasmtime"
edition = "2018"
publish = false

[[bin]]
name = "wasmtime"
path = "src/wasmtime.rs"

[[bin]]
name = "wast"
path = "src/wast.rs"

[[bin]]
name = "wasm2obj"
path = "src/wasm2obj.rs"

[dependencies]
cranelift-codegen = "0.29.0"
cranelift-native = "0.29.0"
wasmtime-debug = { path = "lib/debug" }
wasmtime-environ = { path = "lib/environ" }
wasmtime-runtime = { path = "lib/runtime" }
wasmtime-jit = { path = "lib/jit" }
wasmtime-obj = { path = "lib/obj" }
wasmtime-wast = { path = "lib/wast" }
wasmtime-wasi = { path = "lib/wasi" }
docopt = "1.0.1"
serde = "1.0.75"
serde_derive = "1.0.75"
faerie = "0.7.1"
target-lexicon = { version = "0.2.0", default-features = false }
pretty_env_logger = "0.3.0"
file-per-thread-logger = "0.1.1"
wabt = "0.7"

[workspace]
